name: midterm_project
description: "A new Flutter project for midterm."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
