// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-QvMKo5WjqeTM8rHsMGC30Ol0oSOkjzo',
    appId: '1:502950602225:web:ef0064f98c60bb642e9050',
    messagingSenderId: '502950602225',
    projectId: 'midtermproject-150d2',
    authDomain: 'midtermproject-150d2.firebaseapp.com',
    storageBucket: 'midtermproject-150d2.firebasestorage.app',
    measurementId: 'G-QRTDN5SFS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaPZRyyltZHwfZzWP_fj4IiIYHCYvznY',
    appId: '1:502950602225:android:77080de1e169ee292e9050',
    messagingSenderId: '502950602225',
    projectId: 'midtermproject-150d2',
    storageBucket: 'midtermproject-150d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JlK0HCc2ie-XLejyhjMEmbOfhQvBJaQ',
    appId: '1:502950602225:ios:9615cc4d7937faa22e9050',
    messagingSenderId: '502950602225',
    projectId: 'midtermproject-150d2',
    storageBucket: 'midtermproject-150d2.firebasestorage.app',
    iosBundleId: 'com.example.midtermProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JlK0HCc2ie-XLejyhjMEmbOfhQvBJaQ',
    appId: '1:502950602225:ios:9615cc4d7937faa22e9050',
    messagingSenderId: '502950602225',
    projectId: 'midtermproject-150d2',
    storageBucket: 'midtermproject-150d2.firebasestorage.app',
    iosBundleId: 'com.example.midtermProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-QvMKo5WjqeTM8rHsMGC30Ol0oSOkjzo',
    appId: '1:502950602225:web:04c138c6a1c8beaf2e9050',
    messagingSenderId: '502950602225',
    projectId: 'midtermproject-150d2',
    authDomain: 'midtermproject-150d2.firebaseapp.com',
    storageBucket: 'midtermproject-150d2.firebasestorage.app',
    measurementId: 'G-QTQQBM9S4D',
  );
}
